<?php
/**
 * @file
 *
 */

/**
 * Implements hook_init()
 */
function jobboard_init() {
  drupal_add_css(drupal_get_path('module', 'jobboard') . '/css/jobboard_jobs_common.css');
}

/**
 * Implements hook_menu()
 */
function jobboard_menu() {
  $items = array();

  $items['jobboard/jobs/list'] = array(
    'title' => 'List',
    'page callback' => '_jobboard_jobs_list',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'inc/jobboard_jobs_list.page.inc',
  );

  $items['jobboard/jobs/map'] = array(
    'title' => 'Map',
    'page callback' => '_jobboard_jobs_map',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'inc/jobboard_jobs_map.page.inc',
  );

  $items['jobboard/jobs/dashboard'] = array(
    'title' => 'Dashboard',
    'page callback' => '_jobboard_jobs_dashboard',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'inc/jobboard_jobs_dashboard.page.inc',
  );

  return $items;
}
